openapi: 3.0.3
servers:
- url: /1.0/
info:
  description: Universal Resolver Driver for the `did:iscc` method. See [ISCC DID Method Specification](https://ieps.iscc.codes/iep-0015/)
    for details.
  version: 0.1.1
  title: ISCC DID driver
  contact:
    email: tp@iscc.io
tags:
- name: resolver
  description: Resolves ISCC-IDs as [Decentralized Identifiers (DIDs)](https://www.w3.org/TR/did-core/)
    with the `did:iscc` method
paths:
  /identifiers/{identifier}:
    get:
      operationId: resolve
      summary: Resolve an ISCC DID.
      description: 'This endpoint resolves a DID with the `did:iscc` method. As input it takes
        the DID, plus DID resolution [options](https://www.w3.org/TR/did-core/#did-resolution-options).
        The output is a DID document or resolution result in one of the supported representations.<br><br>

        See the [DID Resolution](https://w3c-ccg.github.io/did-resolution/) specification
        for additional details.'
      tags:
      - resolver
      parameters:
      - in: path
        required: true
        name: identifier
        schema:
          type: string
          format: uri
          pattern: ^did:iscc:[2-7a-z]{10,88}$
          example: did:iscc:miagwptv4j2z57ci
        description: The DID to be resolved using the `iscc` method.
      - in: header
        required: false
        name: Accept
        schema:
          type: string
        description: The requested media type of the DID document representation or DID resolution
          result. See <a href="https://www.w3.org/TR/did-core/#representations">https://www.w3.org/TR/did-core/#representations</a>
          and <a href="https://w3c-ccg.github.io/did-resolution/#did-resolution-result">https://w3c-ccg.github.io/did-resolution/#did-resolution-result</a>.
        examples:
          '*/*':
            value: '*/*'
          application/json:
            value: application/json
          application/ld+json:
            value: application/ld+json
          application/cbor:
            value: application/cbor
      responses:
        '200':
          description: successfully resolved!
        '400':
          description: invalid input!
        '410':
          description: successfully resolved (deactivated)!
        '500':
          description: error!
components:
  schemas:
    ResolutionResult:
      description: The DID resolution result.
      type: object
      additionalProperties: false
      properties:
        didDocument:
          type: object
        didResolutionMetadata:
          type: object
        didDocumentMetadata:
          type: object
    DidDocument:
      description: A DID document
      type: object
      properties:
        '@context':
          type: string
          default: https://www.w3.org/ns/did/v1
          description: The [JSON-LD](https://json-ld.org/) Context URI.
          readOnly: true
        id:
          type: string
          example: did:iscc:miagwptv4j2z57ci
        alsoKnownAs:
          type: string
          example: iscc:kecycpu3okiudz7tybrk5hz4jgptillat2iw7ty7eyiji4qsk5i353i
        controller:
          type: string
          example: did:pkh:eip155:1:0x901ee44e3bddf4bc1c08a2ed229498512f8bcfdc
    DidDocumentMetadata:
      description: DID Document Metadata
      type: object
      properties:
        created:
          type: string
          format: date-time
          example: 2022-08-31 19:08:01+00:00
