# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel, Extra


class ResolutionResult(BaseModel):
    class Config:
        extra = Extra.forbid

    didDocument: Optional[Dict[str, Any]] = None
    didResolutionMetadata: Optional[Dict[str, Any]] = None
    didDocumentMetadata: Optional[Dict[str, Any]] = None
