name: Tests
on: [push, pull_request]

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 2.1.1

      - name: Install Dependencies
        run: poetry install

      - name: Run Tests
        run: poetry run pytest
